### ISSUE TITLE
detail how to make grey wire comments

### ISSUE THREAD

**Issue by richardanaya** [iostapyshyn/wirs#4]

**Comment by iostapyshyn** [comment]
There is no way to set pixels gray through the web interface at the moment. Any colors could be added using an external image editor, such as GIMP. In the end, an exported circuit is a simple png/gif image, which can be opened or edited anywhere.

As far as I remember, only colours which correspond to wires/their respective charges (see [mod.rs](https://github.com/iostapyshyn/wired-logic-rs/blob/2d41d69ce2978dc19737c7f228fe8c5a6633e6c6/src/wired_logic/mod.rs#L9)) are parsed.

**Comment by richardanaya** [comment]
interesting!
