### ISSUE TITLE
add some way to have keyboard keys trigger an energy source

### ISSUE THREAD

**Issue by richardanaya** [iostapyshyn/wirs#5]
it would be neat if there was some kind of keyboard input that could trigger energy sources on and off

**Comment by iostapyshyn** [comment]
Hello Richard,

There is actually a shortcut which partially satisfies your request: pressing "z" creates a source under the mouse pointer. However, it does not delete it when pressed repeatedly. I suppose such functionality wouldn't be hard to implement.

If you wish to implement it, I would be more than happy to accept a pull request. If not, I will probably implement it later. I have a lot of things in my bucket list for this project, although working on Wired-Logic is not in my priorities at the moment.
